spring:
  proflies: 
    active: 
      - dev
---
server:
  port: 8001
eureka:
  client: 
    service-url:                              #客户端注册进eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka/  
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true                   # 访问路径可以显示IP地址
mybatis:
  configuration:
    cache-enabled: true
spring:
  profiles: dev
  application:
    name: microservicecloud-dept 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
info:
  app.name: cplh-microservice
  company.name: cplh

---
server:
  port: 8001
eureka:
  client: 
    service-url:                              #客户端注册进eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka/  
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true                   # 访问路径可以显示IP地址
mybatis:
  configuration:
    cache-enabled: true
spring:
  profiles: test
  application:
    name: microservicecloud-dept 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
info:
  app.name: cplh-microservice
  company.name: cplh


 